ClassRef["NSException"] = {"[:]":"NSObject","[+]":{"exceptionWithName:reason:userInfo:":{"abs":"Creates and returns an exception object .","dec":"+ (NSException *)exceptionWithName:(NSString *)name reason:(NSString *)reason userInfo:(NSDictionary *)userInfo"},"raise:format:":{"abs":"A convenience method that creates and raises an exception.","dec":"+ (void)raise:(NSString *)name format:(NSString *)format, ..."},"raise:format:arguments:":{"abs":"Creates and raises an exception with the specified name, reason, and arguments.","dec":"+ (void)raise:(NSString *)name format:(NSString *)format arguments:(va_list)argList"}},"[-]":{"callStackReturnAddresses":{"abs":"Returns the call return addresses related to a raised exception.","dec":"- (NSArray *)callStackReturnAddresses"},"callStackSymbols":{"abs":"Returns an array containing the current call symbols.","dec":"- (NSArray *)callStackSymbols"},"initWithName:reason:userInfo:":{"abs":"Initializes and returns a newly allocated exception object.","dec":"- (id)initWithName:(NSString *)name reason:(NSString *)reason userInfo:(NSDictionary *)userInfo"},"name":{"abs":"Returns an NSString object used to uniquely identify the receiver.","dec":"- (NSString *)name"},"raise":{"abs":"Raises the receiver, causing program flow to jump to the local exception handler.","dec":"- (void)raise"},"reason":{"abs":"Returns an NSString object containing a “human-readable” reason for the receiver.","dec":"- (NSString *)reason"},"userInfo":{"abs":"Returns an NSDictionary object containing application-specific data pertaining to the receiver.","dec":"- (NSDictionary *)userInfo"}}};